# Generated by Django 5.2.11 on 2026-04-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='indicators_updated',
            field=models.DateTimeField(blank=True, help_text='When indicators were last calculated', null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='ma_20',
            field=models.FloatField(blank=True, help_text='20-day Moving Average', null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='ma_50',
            field=models.FloatField(blank=True, help_text='50-day Moving Average', null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='price_change_pct_30d',
            field=models.FloatField(blank=True, help_text='30-day price change %', null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='price_change_pct_7d',
            field=models.FloatField(blank=True, help_text='7-day price change %', null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='rsi_14',
            field=models.FloatField(blank=True, help_text='14-day RSI', null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='volume_avg_30d',
            field=models.FloatField(blank=True, help_text='30-day average volume', null=True),
        ),
    ]
