# Generated by Django 5.2.11 on 2026-04-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_stock_indicators_updated_stock_ma_20_stock_ma_50_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
