# Generated by Django 5.2.11 on 2026-04-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_nepseinsight_nepseindex'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='nepseindex',
            name='nepse_index_timesta_14fdb5_idx',
        ),
        migrations.AddField(
            model_name='nepseindex',
            name='high',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='nepseindex',
            name='low',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='nepseindex',
            name='open',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='nepseindex',
            name='shares',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nepseindex',
            name='transactions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nepseindex',
            name='turnover',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='nepseindex',
            name='is_minute_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='nepseindex',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='nepseindex',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AddIndex(
            model_name='nepseindex',
            index=models.Index(fields=['-timestamp'], name='market_neps_timesta_72cf00_idx'),
        ),
        migrations.AddIndex(
            model_name='nepseindex',
            index=models.Index(fields=['is_minute_data'], name='market_neps_is_minu_aba5a8_idx'),
        ),
        migrations.AlterModelTable(
            name='nepseindex',
            table=None,
        ),
    ]
