# Generated by Django 5.2.11 on 2026-04-12 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_nepseprediction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkScrapeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_stocks', models.IntegerField(default=0)),
                ('scraped_stocks', models.IntegerField(default=0)),
                ('failed_stocks', models.IntegerField(default=0)),
                ('current_symbol', models.CharField(blank=True, default='', max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulk_scrape_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bulk_scrape_jobs',
                'ordering': ['-started_at'],
            },
        ),
    ]
