# Generated by Django 5.2.11 on 2026-04-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_aiscreeningjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiscreeningjob',
            name='current_stock',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='aiscreeningjob',
            name='stocks_screened',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aiscreeningjob',
            name='total_stocks',
            field=models.IntegerField(default=0),
        ),
    ]
