# Generated by Django 5.2.11 on 2026-06-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_aiscreeningjob_current_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nepseindex',
            name='timestamp',
            field=models.DateTimeField(unique=True),
        ),
    ]
