# Generated by Django 5.2.11 on 2026-04-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_auto_20260412_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='NEPSEInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight', models.TextField()),
                ('time_range', models.CharField(help_text="e.g., '7d', '1d'", max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_market_closed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'nepse_insights',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='NEPSEIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('volume', models.BigIntegerField(default=0)),
                ('is_minute_data', models.BooleanField(default=False, help_text='True for 1-min data, False for daily data')),
            ],
            options={
                'db_table': 'nepse_index',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'is_minute_data'], name='nepse_index_timesta_14fdb5_idx')],
            },
        ),
    ]
