# Generated by Django 5.2.11 on 2026-04-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_remove_nepseindex_nepse_index_timesta_14fdb5_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NEPSEPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(help_text='Day number (1-7)')),
                ('predicted_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('upper_bound', models.DecimalField(decimal_places=2, max_digits=12)),
                ('lower_bound', models.DecimalField(decimal_places=2, max_digits=12)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'nepse_predictions',
                'ordering': ['day'],
            },
        ),
    ]
