"""Pre-defined list of common NEPSE-listed stock symbols"""

NEPSE_STOCKS = [

    # ── COMMERCIAL BANKS ──────────────────────────────────────────────────
    {'symbol': 'ADBL',  'name': 'Agricultural Development Bank',      'sector': 'Commercial Bank'},
    {'symbol': 'CBL',   'name': 'Century Bank',                       'sector': 'Commercial Bank'},
    {'symbol': 'CZBIL', 'name': 'Citizens Bank International',        'sector': 'Commercial Bank'},
    {'symbol': 'EBL',   'name': 'Everest Bank',                       'sector': 'Commercial Bank'},
    {'symbol': 'GBIME', 'name': 'Global IME Bank',                    'sector': 'Commercial Bank'},
    {'symbol': 'HBL',   'name': 'Himalayan Bank',                     'sector': 'Commercial Bank'},
    {'symbol': 'KBL',   'name': 'Kumari Bank',                        'sector': 'Commercial Bank'},
    {'symbol': 'LAXMI', 'name': 'Laxmi Sunrise Bank',                 'sector': 'Commercial Bank'},
    {'symbol': 'MBL',   'name': 'Machhapuchchhre Bank',               'sector': 'Commercial Bank'},
    {'symbol': 'MEGA',  'name': 'Mega Bank Nepal',                    'sector': 'Commercial Bank'},
    {'symbol': 'NABIL', 'name': 'Nabil Bank',                         'sector': 'Commercial Bank'},
    {'symbol': 'NBB',   'name': 'Nepal Bangladesh Bank',              'sector': 'Commercial Bank'},
    {'symbol': 'NBL',   'name': 'Nepal Bank',                         'sector': 'Commercial Bank'},
    {'symbol': 'NCCB',  'name': 'Nepal Credit and Commerce Bank',     'sector': 'Commercial Bank'},
    {'symbol': 'NICA',  'name': 'NIC Asia Bank',                      'sector': 'Commercial Bank'},
    {'symbol': 'NMB',   'name': 'NMB Bank',                           'sector': 'Commercial Bank'},
    {'symbol': 'PCBL',  'name': 'Prime Commercial Bank',              'sector': 'Commercial Bank'},
    {'symbol': 'PRVU',  'name': 'Prabhu Bank',                        'sector': 'Commercial Bank'},
    {'symbol': 'SANIMA','name': 'Sanima Bank',                        'sector': 'Commercial Bank'},
    {'symbol': 'SBL',   'name': 'Sunrise Bank',                       'sector': 'Commercial Bank'},
    {'symbol': 'SCB',   'name': 'Standard Chartered Bank Nepal',      'sector': 'Commercial Bank'},
    {'symbol': 'SRBL',  'name': 'Siddhartha Bank',                    'sector': 'Commercial Bank'},

    # ── DEVELOPMENT BANKS ─────────────────────────────────────────────────
    {'symbol': 'CORBL', 'name': 'Corporate Development Bank',         'sector': 'Development Bank'},
    {'symbol': 'EDBL',  'name': 'Excel Development Bank',             'sector': 'Development Bank'},
    {'symbol': 'GBBL',  'name': 'Garima Bikas Bank',                  'sector': 'Development Bank'},
    {'symbol': 'GDBL',  'name': 'Green Development Bank',             'sector': 'Development Bank'},
    {'symbol': 'JBBL',  'name': 'Jyoti Bikas Bank',                   'sector': 'Development Bank'},
    {'symbol': 'KBBL',  'name': 'Kamana Sewa Bikas Bank',             'sector': 'Development Bank'},
    {'symbol': 'KRBL',  'name': 'Kriti Development Bank',             'sector': 'Development Bank'},
    {'symbol': 'LBBL',  'name': 'Lumbini Bikas Bank',                 'sector': 'Development Bank'},
    {'symbol': 'MBBL',  'name': 'Muktinath Bikas Bank',               'sector': 'Development Bank'},
    {'symbol': 'MDBL',  'name': 'Miteri Development Bank',            'sector': 'Development Bank'},
    {'symbol': 'MDB',   'name': 'Mahalaxmi Development Bank',         'sector': 'Development Bank'},
    {'symbol': 'MNBBL', 'name': 'Manakamana Development Bank',        'sector': 'Development Bank'},
    {'symbol': 'NABBC', 'name': 'Narayani Development Bank',          'sector': 'Development Bank'},
    {'symbol': 'NESDO', 'name': 'Nesdo Merchant Bank',                'sector': 'Development Bank'},
    {'symbol': 'NGBBL', 'name': 'Nepal Grameen Bikas Bank',           'sector': 'Development Bank'},
    {'symbol': 'SAPDBL','name': 'Saptakoshi Development Bank',        'sector': 'Development Bank'},
    {'symbol': 'SHINE', 'name': 'Shine Resunga Development Bank',     'sector': 'Development Bank'},
    {'symbol': 'SINDU', 'name': 'Sindhu Bikas Bank',                  'sector': 'Development Bank'},

    # ── FINANCE COMPANIES ─────────────────────────────────────────────────
    {'symbol': 'BFC',   'name': 'Bestway Finance',                    'sector': 'Finance'},
    {'symbol': 'CFCL',  'name': 'Central Finance',                    'sector': 'Finance'},
    {'symbol': 'GFCL',  'name': 'Goodwill Finance',                   'sector': 'Finance'},
    {'symbol': 'GUFL',  'name': 'Gurkhas Finance',                    'sector': 'Finance'},
    {'symbol': 'ICFC',  'name': 'ICFC Finance',                       'sector': 'Finance'},
    {'symbol': 'JFL',   'name': 'Janaki Finance',                     'sector': 'Finance'},
    {'symbol': 'MFIL',  'name': 'Multipurpose Finance',               'sector': 'Finance'},
    {'symbol': 'NHDL',  'name': 'Nepal Housing Development Finance',  'sector': 'Finance'},
    {'symbol': 'PFL',   'name': 'Pokhara Finance',                    'sector': 'Finance'},
    {'symbol': 'PROFL', 'name': 'Progressive Finance',                'sector': 'Finance'},
    {'symbol': 'RLFL',  'name': 'Reliance Finance',                   'sector': 'Finance'},
    {'symbol': 'RSDC',  'name': 'Riddhi Siddhi Laghubitta',           'sector': 'Finance'},
    {'symbol': 'SFCL',  'name': 'Sewa Finance',                       'sector': 'Finance'},
    {'symbol': 'SIFC',  'name': 'Shree Investment Finance',           'sector': 'Finance'},

    # ── LIFE INSURANCE ────────────────────────────────────────────────────
    {'symbol': 'ALICL', 'name': 'Asian Life Insurance',               'sector': 'Life Insurance'},
    {'symbol': 'CLI',   'name': 'Citizen Life Insurance',             'sector': 'Life Insurance'},
    {'symbol': 'GILC',  'name': 'Gurans Life Insurance',              'sector': 'Life Insurance'},
    {'symbol': 'ILI',   'name': 'IME Life Insurance',                 'sector': 'Life Insurance'},
    {'symbol': 'JLIC',  'name': 'Jyoti Life Insurance',               'sector': 'Life Insurance'},
    {'symbol': 'LICN',  'name': 'Life Insurance Corporation Nepal',   'sector': 'Life Insurance'},
    {'symbol': 'LLBS',  'name': 'Laxmi Life Insurance',               'sector': 'Life Insurance'},
    {'symbol': 'MNBJA', 'name': 'Met Life Insurance',                 'sector': 'Life Insurance'},
    {'symbol': 'NLIC',  'name': 'National Life Insurance',            'sector': 'Life Insurance'},
    {'symbol': 'NLICL', 'name': 'Nepal Life Insurance',               'sector': 'Life Insurance'},
    {'symbol': 'PLI',   'name': 'Prime Life Insurance',               'sector': 'Life Insurance'},
    {'symbol': 'RLIC',  'name': 'Rastriya Beema Company',             'sector': 'Life Insurance'},
    {'symbol': 'SNLI',  'name': 'Sun Nepal Life Insurance',           'sector': 'Life Insurance'},
    {'symbol': 'SRLI',  'name': 'Sunrise Life Insurance',             'sector': 'Life Insurance'},
    {'symbol': 'SJLIC', 'name': 'Sanima Life Insurance',              'sector': 'Life Insurance'},

    # ── NON-LIFE INSURANCE ────────────────────────────────────────────────
    {'symbol': 'AIL',   'name': 'Ajod Insurance',                     'sector': 'Non-Life Insurance'},
    {'symbol': 'ANLB',  'name': 'Annapurna Life',                     'sector': 'Non-Life Insurance'},
    {'symbol': 'HGI',   'name': 'Himalayan General Insurance',        'sector': 'Non-Life Insurance'},
    {'symbol': 'IGI',   'name': 'IME General Insurance',              'sector': 'Non-Life Insurance'},
    {'symbol': 'LGIL',  'name': 'Laxmi General Insurance',            'sector': 'Non-Life Insurance'},
    {'symbol': 'NICA',  'name': 'NIC Asia Insurance',                 'sector': 'Non-Life Insurance'},
    {'symbol': 'NIL',   'name': 'Neco Insurance',                     'sector': 'Non-Life Insurance'},
    {'symbol': 'NLG',   'name': 'Nepal Life and General Insurance',   'sector': 'Non-Life Insurance'},
    {'symbol': 'NICL',  'name': 'National Insurance Company',         'sector': 'Non-Life Insurance'},
    {'symbol': 'PIC',   'name': 'Premier Insurance',                  'sector': 'Non-Life Insurance'},
    {'symbol': 'PICL',  'name': 'Prudential Insurance',               'sector': 'Non-Life Insurance'},
    {'symbol': 'PRIN',  'name': 'Prabhu Insurance',                   'sector': 'Non-Life Insurance'},
    {'symbol': 'RBCL',  'name': 'Rastriya Beema Company (General)',   'sector': 'Non-Life Insurance'},
    {'symbol': 'SGIC',  'name': 'Sagarmatha Insurance',               'sector': 'Non-Life Insurance'},
    {'symbol': 'SICL',  'name': 'Sanima General Insurance',           'sector': 'Non-Life Insurance'},
    {'symbol': 'SIC',   'name': 'Shikhar Insurance',                  'sector': 'Non-Life Insurance'},
    {'symbol': 'UAIL',  'name': 'United Ajod Insurance',              'sector': 'Non-Life Insurance'},

    # ── HYDROPOWER ────────────────────────────────────────────────────────
    {'symbol': 'AHPC',  'name': 'Arun Himalayan Hydro',               'sector': 'Hydropower'},
    {'symbol': 'API',   'name': 'Arun Valley Hydropower',             'sector': 'Hydropower'},
    {'symbol': 'BARUN', 'name': 'Barun Hydropower Company',           'sector': 'Hydropower'},
    {'symbol': 'BEDC',  'name': 'Butwal Electric Company',            'sector': 'Hydropower'},
    {'symbol': 'BHDC',  'name': 'Barahathawa Hydropower',             'sector': 'Hydropower'},
    {'symbol': 'BPCL',  'name': 'Bhote Koshi Power Company',          'sector': 'Hydropower'},
    {'symbol': 'BPL',   'name': 'Budhigandaki Power Limited',         'sector': 'Hydropower'},
    {'symbol': 'CHCL',  'name': 'Chilime Hydropower',                 'sector': 'Hydropower'},
    {'symbol': 'DHPL',  'name': 'Dhawalagiri Hydropower',             'sector': 'Hydropower'},
    {'symbol': 'DORDI', 'name': 'Dordi Khola Hydropower',             'sector': 'Hydropower'},
    {'symbol': 'EHPL',  'name': 'Eastern Hydropower',                 'sector': 'Hydropower'},
    {'symbol': 'GHL',   'name': 'Gandaki Hydropower',                 'sector': 'Hydropower'},
    {'symbol': 'GRDBL', 'name': 'Garuda Bikas Bank',                  'sector': 'Hydropower'},
    {'symbol': 'HDHPC', 'name': 'Himalayan Distillery (Hydro)',       'sector': 'Hydropower'},
    {'symbol': 'HIDCL', 'name': 'Hydroelectricity Investment Dev.',   'sector': 'Hydropower'},
    {'symbol': 'HPPL',  'name': 'Himalayan Power Partner',            'sector': 'Hydropower'},
    {'symbol': 'HURJA', 'name': 'Hurja Power Company',                'sector': 'Hydropower'},
    {'symbol': 'JOSHI', 'name': 'Joshi Hydropower',                   'sector': 'Hydropower'},
    {'symbol': 'KBHG',  'name': 'Kabeli Bhanjyang Hydropower',        'sector': 'Hydropower'},
    {'symbol': 'KKHC',  'name': 'Kaski Hydropower Company',           'sector': 'Hydropower'},
    {'symbol': 'KKHL',  'name': 'Kalinchowk Hydropower',              'sector': 'Hydropower'},
    {'symbol': 'KPCL',  'name': 'Kalika Power Company',               'sector': 'Hydropower'},
    {'symbol': 'KRHM',  'name': 'Karnali Hydropower',                 'sector': 'Hydropower'},
    {'symbol': 'KSBBL', 'name': 'Koshi Bikash Bank (Hydro)',          'sector': 'Hydropower'},
    {'symbol': 'MBJC',  'name': 'Madi Bijuli Company',                'sector': 'Hydropower'},
    {'symbol': 'MCHL',  'name': 'Mailung Khola Hydropower',           'sector': 'Hydropower'},
    {'symbol': 'MHNL',  'name': 'Marsyangdi Hydropower Nepal',        'sector': 'Hydropower'},
    {'symbol': 'MKHL',  'name': 'Manakamana Hydropower',              'sector': 'Hydropower'},
    {'symbol': 'MMKJL', 'name': 'Mirmire Laghubitta (Hydro)',         'sector': 'Hydropower'},
    {'symbol': 'MHL',   'name': 'Madhya Bhotekoshi Hydropower',       'sector': 'Hydropower'},
    {'symbol': 'NHPC',  'name': 'National Hydropower Company',        'sector': 'Hydropower'},
    {'symbol': 'NHDCL', 'name': 'Nepal Hydro Developers',             'sector': 'Hydropower'},
    {'symbol': 'NPCL',  'name': 'Nepal Power Company',                'sector': 'Hydropower'},
    {'symbol': 'PPCL',  'name': 'Panchakanya Mai Hydropower',         'sector': 'Hydropower'},
    {'symbol': 'PMHPL', 'name': 'Provident Micro Hydro Power',        'sector': 'Hydropower'},
    {'symbol': 'RADHI', 'name': 'Radhi Bidyut Company',               'sector': 'Hydropower'},
    {'symbol': 'RAWA',  'name': 'Rawa Energy Development',            'sector': 'Hydropower'},
    {'symbol': 'RHJC',  'name': 'Rairang Hydropower Dev Company',     'sector': 'Hydropower'},
    {'symbol': 'RHPC',  'name': 'Ridi Hydropower Dev Company',        'sector': 'Hydropower'},
    {'symbol': 'RIDI',  'name': 'Ridi Hydropower',                    'sector': 'Hydropower'},
    {'symbol': 'RLEL',  'name': 'Ridge Line Energy',                  'sector': 'Hydropower'},
    {'symbol': 'RMHPL', 'name': 'Ruru Micro Hydro Power',             'sector': 'Hydropower'},
    {'symbol': 'RRHPL', 'name': 'Rastriya Hydropower (Ridi)',         'sector': 'Hydropower'},
    {'symbol': 'SGHC',  'name': 'Swet-Ganga Hydropower',              'sector': 'Hydropower'},
    {'symbol': 'SKBBL', 'name': 'Seti Khola Bijuli Bazar',            'sector': 'Hydropower'},
    {'symbol': 'SKHL',  'name': 'Super Khudi Hydropower',             'sector': 'Hydropower'},
    {'symbol': 'SKHEL', 'name': 'Suryakunda Hydro Electric',          'sector': 'Hydropower'},
    {'symbol': 'SMHL',  'name': 'Solu Multi-purpose Hydropower',      'sector': 'Hydropower'},
    {'symbol': 'SSHL',  'name': 'Solu Simara Hydropower',             'sector': 'Hydropower'},
    {'symbol': 'TMHL',  'name': 'Tama Koshi Hydropower',              'sector': 'Hydropower'},
    {'symbol': 'TRHPL', 'name': 'Trishuli Hydropower',                'sector': 'Hydropower'},
    {'symbol': 'UNHPL', 'name': 'Upper Nyadi Hydropower',             'sector': 'Hydropower'},
    {'symbol': 'UMRH',  'name': 'Upper Marsyangdi Hydropower',        'sector': 'Hydropower'},
    {'symbol': 'UPCL',  'name': 'Upper Tamakoshi Hydropower',         'sector': 'Hydropower'},
    {'symbol': 'YPRD',  'name': 'Yadav Prakash Renewable Energy',     'sector': 'Hydropower'},

    # ── MICROFINANCE ──────────────────────────────────────────────────────
    {'symbol': 'ACLBSL','name': 'Aarambha Chautari Laghubitta',       'sector': 'Microfinance'},
    {'symbol': 'ALBSL', 'name': 'Adhikhola Laghubitta',               'sector': 'Microfinance'},
    {'symbol': 'ANLBSL','name': 'Annapurna Laghubitta',               'sector': 'Microfinance'},
    {'symbol': 'CBBL',  'name': 'Chhimek Laghubitta',                 'sector': 'Microfinance'},
    {'symbol': 'DDBL',  'name': 'Deprosc Laghubitta',                 'sector': 'Microfinance'},
    {'symbol': 'FMDBL', 'name': 'Forward Microfinance',               'sector': 'Microfinance'},
    {'symbol': 'FOWAD', 'name': 'Fowad Microfinance',                 'sector': 'Microfinance'},
    {'symbol': 'GMFBS', 'name': 'Grameen Bikas Laghubitta',           'sector': 'Microfinance'},
    {'symbol': 'HLBSL', 'name': 'Himalayan Laghubitta',               'sector': 'Microfinance'},
    {'symbol': 'ILBSL', 'name': 'Infinity Laghubitta',                'sector': 'Microfinance'},
    {'symbol': 'JSLBB', 'name': 'Jalpa Samudayik Laghubitta',         'sector': 'Microfinance'},
    {'symbol': 'KLBSL', 'name': 'Kalika Laghubitta',                  'sector': 'Microfinance'},
    {'symbol': 'LLBSL', 'name': 'Laxmi Laghubitta',                   'sector': 'Microfinance'},
    {'symbol': 'MERO',  'name': 'Mero Microfinance',                  'sector': 'Microfinance'},
    {'symbol': 'MLBBL', 'name': 'Mahila Laghubitta',                  'sector': 'Microfinance'},
    {'symbol': 'MLBS',  'name': 'Manushi Laghubitta',                 'sector': 'Microfinance'},
    {'symbol': 'MMFDB', 'name': 'Mirmire Microfinance',               'sector': 'Microfinance'},
    {'symbol': 'MNBBL', 'name': 'Manakamana Laghubitta',              'sector': 'Microfinance'},
    {'symbol': 'NADEP', 'name': 'NADEP Laghubitta',                   'sector': 'Microfinance'},
    {'symbol': 'NESDO', 'name': 'Nesdo Merchant Finance',             'sector': 'Microfinance'},
    {'symbol': 'NMLBBL','name': 'National Microfinance Laghubitta',   'sector': 'Microfinance'},
    {'symbol': 'NMFBS', 'name': 'NMB Microfinance',                   'sector': 'Microfinance'},
    {'symbol': 'NSEWA', 'name': 'Naya Sewa Laghubitta',               'sector': 'Microfinance'},
    {'symbol': 'RSDC',  'name': 'Riddhi Siddhi Laghubitta',           'sector': 'Microfinance'},
    {'symbol': 'SAMAJ', 'name': 'Samaj Laghubitta',                   'sector': 'Microfinance'},
    {'symbol': 'SHLB',  'name': 'Sana Kisan Laghubitta',              'sector': 'Microfinance'},
    {'symbol': 'SKBBL', 'name': 'Sana Kisan Bikas Laghubitta',        'sector': 'Microfinance'},
    {'symbol': 'SLBBL', 'name': 'Sworojagar Laghubitta',              'sector': 'Microfinance'},
    {'symbol': 'SMFDB', 'name': 'Support Microfinance',               'sector': 'Microfinance'},
    {'symbol': 'SWBBL', 'name': 'Swabhiman Laghubitta',               'sector': 'Microfinance'},
    {'symbol': 'ULBSL', 'name': 'Unnati Laghubitta',                  'sector': 'Microfinance'},
    {'symbol': 'VLBS',  'name': 'Vijaya Laghubitta',                  'sector': 'Microfinance'},
    {'symbol': 'WOMI',  'name': 'Women Micro Financial Institution',  'sector': 'Microfinance'},

    # ── HOTELS & TOURISM ──────────────────────────────────────────────────
    {'symbol': 'CGH',   'name': 'Chandragiri Hills',                  'sector': 'Hotels & Tourism'},
    {'symbol': 'HFIN',  'name': 'Hotel Forest Inn',                   'sector': 'Hotels & Tourism'},
    {'symbol': 'OHL',   'name': 'Oriental Hotels',                    'sector': 'Hotels & Tourism'},
    {'symbol': 'SHL',   'name': 'Soaltee Hotel',                      'sector': 'Hotels & Tourism'},
    {'symbol': 'TRH',   'name': 'Taragaon Regency Hotels',            'sector': 'Hotels & Tourism'},
    {'symbol': 'TUDC',  'name': 'Tourism Development Corporation',    'sector': 'Hotels & Tourism'},
    {'symbol': 'YHL',   'name': 'Yak and Yeti Hotels',                'sector': 'Hotels & Tourism'},

    # ── MANUFACTURING & PROCESSING ────────────────────────────────────────
    {'symbol': 'BNL',   'name': 'Bottlers Nepal (Balaju)',            'sector': 'Manufacturing'},
    {'symbol': 'BNLT',  'name': 'Bottlers Nepal (Terai)',             'sector': 'Manufacturing'},
    {'symbol': 'BSL',   'name': 'Biratnagar Jute Mills',              'sector': 'Manufacturing'},
    {'symbol': 'HDL',   'name': 'Himalayan Distillery',               'sector': 'Manufacturing'},
    {'symbol': 'NKU',   'name': 'Nepal Knitwear',                     'sector': 'Manufacturing'},
    {'symbol': 'NLO',   'name': 'Nepal Lube Oil',                     'sector': 'Manufacturing'},
    {'symbol': 'NRJL',  'name': 'NRN Infrastructure Development',     'sector': 'Manufacturing'},
    {'symbol': 'NTC',   'name': 'Nepal Telecom',                      'sector': 'Manufacturing'},
    {'symbol': 'PCBL',  'name': 'Palpa Cement Industries',            'sector': 'Manufacturing'},
    {'symbol': 'RSML',  'name': 'Reliance Spinning Mills',            'sector': 'Manufacturing'},
    {'symbol': 'SAIL',  'name': 'Shreenagar Agritech Industries',     'sector': 'Manufacturing'},
    {'symbol': 'SHIVM', 'name': 'Shivam Cements',                     'sector': 'Manufacturing'},
    {'symbol': 'SYPNL', 'name': 'SY Panel Nepal',                    'sector': 'Manufacturing'},
    {'symbol': 'UNL',   'name': 'Unilever Nepal',                     'sector': 'Manufacturing'},

    # ── TRADING ───────────────────────────────────────────────────────────
    {'symbol': 'BBC',   'name': 'Bishal Bazar Company',               'sector': 'Trading'},
    {'symbol': 'STC',   'name': 'Salt Trading Corporation',           'sector': 'Trading'},

    # ── INVESTMENT ────────────────────────────────────────────────────────
    {'symbol': 'CIT',   'name': 'Citizen Investment Trust',           'sector': 'Investment'},
    {'symbol': 'HIDCL', 'name': 'Hydroelectricity Investment Dev.',   'sector': 'Investment'},
    {'symbol': 'NIDC',  'name': 'Nepal Industrial Dev. Corporation',  'sector': 'Investment'},
    {'symbol': 'NRN',   'name': 'NRN Infrastructure & Development',   'sector': 'Investment'},
    {'symbol': 'RHPC',  'name': 'Rastriya Hydropower Dev Company',    'sector': 'Investment'},
]

SECTORS = sorted(list(set(s["sector"] for s in NEPSE_STOCKS)))
